services:
  db: 
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: docker
  
  web:
    build:
      context: .
    command: bash -c "rm -f tmp/pids/server.pid && exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/rails

    ports:
      - "3000:3000"
    depends_on:
      - db